# Generated by Django 5.0.1 on 2024-02-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaltask',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
