# Generated by Django 5.0.2 on 2024-03-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
